# Site
name: "Kristian Boda"
title: "Kristian Boda"
description: "Kristian Boda"
logo: 'assets/images/bodak.png'
favicon: https://github.githubassets.com/favicons/favicon.png
baseurl: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  bodak:
    display_name: Kristian Boda
    avatar: /assets/images/bodak.png

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

issues_repo: bodak/bodak.github.io

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [Gemfile, Gemfile.lock]
